spring:
  application:
    name: DetailingStudio

  # PostgreSQL configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql:///detailing_studio?cloudSqlInstance=project-f0c6dffa-7d80-4aef-9b0:europe-west3:a767891abrisa&socketFactory=com.google.cloud.sql.postgres.SocketFactory}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:numb151515!A}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # Spring Security
  security:
    # Managed via database auth now
    {}

server:
  port: 8080

# Application custom properties
app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:brisa2026}
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000,https://detailing-frontend-518542558773.europe-west3.run.app
  s3:
    endpoint: ${R2_ENDPOINT:https://b570f853bda76e7e510fbe098d826a55.r2.cloudflarestorage.com}
    bucket: ${R2_BUCKET:detailing}
    access-key: ${R2_ACCESS_KEY:d88b16b1c2ffdfd6dd39e67a8cec4cc1}
    secret-key: ${R2_SECRET_KEY:3aafb13e02b0c677516857dd9a41451462cc20b8aba0b71994bbcabfb981d99e}
    region: ${R2_REGION:auto}
    public-url-prefix: ${R2_PUBLIC_URL:https://pub-your_pub_id.r2.dev}

