name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-f0c6dffa-7d80-4aef-9b0
  REGION: europe-west3
  GAR_LOCATION: europe-west3-docker.pkg.dev
  REPOSITORY: detailing-repo
  BACKEND_IMAGE: app
  FRONTEND_IMAGE: frontend
  BACKEND_SERVICE: detailing-backend
  FRONTEND_SERVICE: detailing-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/518542558773/locations/global/workloadIdentityPools/github/providers/github-provider'
          service_account: '518542558773-compute@developer.gserviceaccount.com'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }} --quiet

      - name: Build and Push Backend
        run: |-
          TAG=${{ github.sha }}
          IMAGE_PATH=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.BACKEND_IMAGE }}
          docker build -t $IMAGE_PATH:$TAG -t $IMAGE_PATH:latest .
          docker push $IMAGE_PATH:$TAG
          docker push $IMAGE_PATH:latest

      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.BACKEND_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          env_vars: |
            SPRING_PROFILES_ACTIVE=h2
          flags: '--allow-unauthenticated --port=8080'

      - name: Build and Push Frontend
        run: |-
          TAG=${{ github.sha }}
          IMAGE_PATH=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FRONTEND_IMAGE }}
          docker build -t $IMAGE_PATH:$TAG -t $IMAGE_PATH:latest ./frontend
          docker push $IMAGE_PATH:$TAG
          docker push $IMAGE_PATH:latest

      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.FRONTEND_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          flags: '--allow-unauthenticated --port=80'
