export default {
  nav: { home: 'Inicio', services: 'Servicios', contact: 'Contacto', booking: 'Reservar', admin: 'Admin', language: 'Idioma' },
  hero: { title: 'Detailing Móvil', titleHighlight: 'Premium', subtitle: 'Llevamos el showroom a tu puerta. Pulido profesional, restauración y limpieza profunda — donde tú estés.', cta: 'Reserva Tu Sesión', ctaSecondary: 'Nuestros Servicios' },
  services: { title: 'Nuestros Servicios', subtitle: 'Cuidado profesional para cada detalle de tu vehículo', duration: '{minutes} min', from: 'desde' },
  why: { title: '¿Por Qué Elegir BRISA Mobile Detailing?', mobile: { title: 'Servicio Móvil', desc: 'Vamos a tu ubicación — hogar, oficina o donde sea conveniente.' }, professional: { title: 'Equipamiento Profesional', desc: 'Herramientas líderes en la industria y productos premium.' }, experience: { title: 'Equipo Experto', desc: 'Años de experiencia con todo tipo de vehículos.' }, guarantee: { title: 'Garantía de Calidad', desc: '100% satisfacción garantizada.' } },
  cta: { title: '¿Listo Para Transformar Tu Vehículo?', subtitle: 'Reserva tu cita hoy y experimenta la diferencia BRISA Mobile Detailing.', button: 'Reservar Ahora' },
  booking: { title: 'Reserva Tu Sesión', steps: { services: 'Servicios', datetime: 'Fecha y Hora', contact: 'Contacto', photos: 'Fotos', confirm: 'Confirmar' }, selectServices: 'Selecciona Servicios', selectDate: 'Selecciona Fecha', selectTime: 'Selecciona Horario', totalDuration: 'Duración Total', minutes: 'min', noSlots: 'No hay horarios disponibles para esta fecha', notWorkingDay: 'Este día no es laborable', contact: { phone: 'Teléfono', phonePlaceholder: '+34 600 123 456', email: 'Email (opcional)', emailPlaceholder: 'tu@email.com', whatsapp: 'WhatsApp', whatsappPlaceholder: '+34 600 123 456', instagram: 'Instagram', instagramPlaceholder: '@tucuenta', address: 'Tu Dirección', addressPlaceholder: 'Calle Principal 123, Ciudad', notes: 'Notas Adicionales (opcional)', notesPlaceholder: 'Solicitudes especiales o detalles sobre tu vehículo...' }, photos: { title: 'Subir Fotos del Vehículo', subtitle: 'Agrega fotos de tu vehículo para estimar mejor el tiempo de trabajo', dropzone: 'Arrastra fotos aquí o haz clic para buscar', maxSize: 'Máximo 10MB por archivo' }, summary: { title: 'Resumen de Reserva', services: 'Servicios Seleccionados', dateTime: 'Fecha y Hora', duration: 'Duración Total', contact: 'Información de Contacto', photos: 'Fotos', photosCount: '{count} foto(s) adjunta(s)', submit: 'Confirmar Reserva', submitting: 'Enviando...' }, success: { title: '¡Reserva Confirmada!', message: 'Gracias por elegir BRISA Mobile Detailing. Te contactaremos pronto para confirmar tu cita.', backHome: 'Volver al Inicio', bookAnother: 'Reservar Otra Sesión' }, next: 'Continuar', prev: 'Atrás' },
  admin: { login: { title: 'Acceso Admin', username: 'Usuario', password: 'Contraseña', submit: 'Entrar', error: 'Credenciales inválidas' }, tabs: { bookings: 'Reservas', services: 'Servicios', schedule: 'Horario' }, bookings: { title: 'Gestionar Reservas', noBookings: 'Sin reservas aún', status: 'Estado', customer: 'Cliente', services: 'Servicios', dateTime: 'Fecha y Hora', duration: 'Duración', actions: 'Acciones', confirm: 'Confirmar', complete: 'Completar', cancel: 'Cancelar', delete: 'Eliminar', viewPhotos: 'Ver Fotos' }, services: { title: 'Gestionar Servicios', addNew: 'Agregar Servicio', name: 'Nombre', description: 'Descripción', duration: 'Duración (min)', price: 'Precio', active: 'Activo', save: 'Guardar', cancel: 'Cancelar', edit: 'Editar', delete: 'Desactivar' }, schedule: { title: 'Horario Laboral', day: 'Día', start: 'Inicio', end: 'Fin', working: 'Laborable', save: 'Guardar Horario', breaks: 'Configuración de Descansos', breakBetween: 'Descanso Entre Citas (min)', lunchStart: 'Inicio Almuerzo', lunchEnd: 'Fin Almuerzo', saveBreaks: 'Guardar Descansos' }, logout: 'Cerrar Sesión' },
  days: { MONDAY: 'Lunes', TUESDAY: 'Martes', WEDNESDAY: 'Miércoles', THURSDAY: 'Jueves', FRIDAY: 'Viernes', SATURDAY: 'Sábado', SUNDAY: 'Domingo' },
  footer: { rights: '© 2026 BRISA Mobile Detailing. Todos los derechos reservados.', tagline: 'Detailing Móvil Premium' },
  contact: { title: 'Contactenos', subtitle: 'Disponibles 24/7 — llama, escribe o Instagram.', callOrText: 'Llama o Escribe 24/7', available: 'Disponibles todo el dia', instagram: 'Instagram', instagramHint: 'Ver nuestro trabajo', area: 'Area de servicio', areaValue: 'Jacksonville & St. Augustine', areaHint: 'Vamos a tu ubicacion' }
}
