export default {
  nav: { home: 'Главная', services: 'Услуги', contact: 'Контакты', booking: 'Записаться', admin: 'Админ', language: 'Язык' },
  hero: { title: 'Премиальный Мобильный', titleHighlight: 'Авто Детейлинг', subtitle: 'Мы привозим шоурум к вашим дверям. Профессиональная полировка, реставрация и глубокая чистка — где бы вы ни были.', cta: 'Записаться', ctaSecondary: 'Наши Услуги' },
  services: { title: 'Наши Услуги', subtitle: 'Профессиональный уход за каждой деталью вашего автомобиля', duration: '{minutes} мин', from: 'от' },
  why: { title: 'Почему BRISA Mobile Detailing?', mobile: { title: 'Мобильный Сервис', desc: 'Мы приезжаем к вашей локации — дом, офис или любое удобное место.' }, professional: { title: 'Профессиональное Оборудование', desc: 'Лучшие инструменты и премиальные продукты для безупречного результата.' }, experience: { title: 'Команда Экспертов', desc: 'Годы опыта со всеми типами автомобилей и систем окраски.' }, guarantee: { title: 'Гарантия Качества', desc: '100% гарантия удовлетворения или мы вернёмся исправить.' } },
  cta: { title: 'Готовы Преобразить Ваш Автомобиль?', subtitle: 'Запишитесь сегодня и почувствуйте разницу BRISA Mobile Detailing.', button: 'Записаться' },
  booking: { title: 'Запись на Сессию', steps: { services: 'Услуги', datetime: 'Дата и Время', contact: 'Контакты', photos: 'Фото', confirm: 'Подтверждение' }, selectServices: 'Выберите Услуги', selectDate: 'Выберите Дату', selectTime: 'Выберите Время', totalDuration: 'Общая Длительность', minutes: 'мин', noSlots: 'Нет доступных слотов на эту дату', notWorkingDay: 'Этот день не является рабочим', contact: { phone: 'Номер Телефона', phonePlaceholder: '+7 900 123 4567', email: 'Email (необязательно)', emailPlaceholder: 'ваш@email.com', whatsapp: 'WhatsApp', whatsappPlaceholder: '+7 900 123 4567', instagram: 'Instagram', instagramPlaceholder: '@вашаккаунт', address: 'Ваш Адрес / Локация', addressPlaceholder: 'ул. Главная 123, Город', notes: 'Дополнительные Заметки (необязательно)', notesPlaceholder: 'Особые пожелания или детали о вашем автомобиле...' }, photos: { title: 'Загрузить Фото Автомобиля', subtitle: 'Добавьте фото вашего авто для точной оценки времени работы', dropzone: 'Перетащите фото сюда или нажмите для выбора', maxSize: 'Макс 10МБ на файл' }, summary: { title: 'Итог Записи', services: 'Выбранные Услуги', dateTime: 'Дата и Время', duration: 'Общая Длительность', contact: 'Контактная Информация', photos: 'Фото', photosCount: '{count} фото добавлено', submit: 'Подтвердить Запись', submitting: 'Отправляется...' }, success: { title: 'Запись Подтверждена!', message: 'Спасибо за выбор BRISA Mobile Detailing. Мы свяжемся с вами в ближайшее время.', backHome: 'На Главную', bookAnother: 'Записаться Ещё' }, next: 'Далее', prev: 'Назад' },
  admin: { login: { title: 'Вход Администратора', username: 'Логин', password: 'Пароль', submit: 'Войти', error: 'Неверные данные' }, tabs: { bookings: 'Записи', services: 'Услуги', schedule: 'Расписание' }, bookings: { title: 'Управление Записями', noBookings: 'Записей ещё нет', status: 'Статус', customer: 'Клиент', services: 'Услуги', dateTime: 'Дата и Время', duration: 'Длительность', actions: 'Действия', confirm: 'Подтвердить', complete: 'Завершить', cancel: 'Отменить', delete: 'Удалить', viewPhotos: 'Просмотреть Фото' }, services: { title: 'Управление Услугами', addNew: 'Добавить Услугу', name: 'Название', description: 'Описание', duration: 'Длительность (мин)', price: 'Цена', active: 'Активна', save: 'Сохранить', cancel: 'Отмена', edit: 'Редактировать', delete: 'Деактивировать' }, schedule: { title: 'Рабочее Расписание', day: 'День', start: 'Начало', end: 'Конец', working: 'Рабочий', save: 'Сохранить Расписание', breaks: 'Настройка Перерывов', breakBetween: 'Перерыв Между Записями (мин)', lunchStart: 'Начало Обеда', lunchEnd: 'Конец Обеда', saveBreaks: 'Сохранить Перерывы' }, logout: 'Выйти' },
  days: { MONDAY: 'Понедельник', TUESDAY: 'Вторник', WEDNESDAY: 'Среда', THURSDAY: 'Четверг', FRIDAY: 'Пятница', SATURDAY: 'Суббота', SUNDAY: 'Воскресенье' },
  footer: { rights: '© 2026 BRISA Mobile Detailing. Все права защищены.', tagline: 'Премиальный Мобильный Авто Детейлинг' },
  contact: { title: 'Свяжитесь с нами', subtitle: 'Доступны круглосуточно — звоните, пишите или Instagram.', callOrText: 'Звоните или Пишите 24/7', available: 'Доступны круглосуточно', instagram: 'Instagram', instagramHint: 'Наши последние работы', area: 'Зона обслуживания', areaValue: 'Jacksonville & St. Augustine', areaHint: 'Приезжаем к вам' }
}
