export default {
  nav: { home: 'Головна', services: 'Послуги', booking: 'Записатися', admin: 'Адмін', language: 'Мова' },
  hero: { title: 'Преміальний Мобільний', titleHighlight: 'Авто Детейлінг', subtitle: 'Ми привозимо шоурум до ваших дверей. Професійне полірування, відновлення та глибоке очищення — де б ви не були.', cta: 'Записатися', ctaSecondary: 'Наші Послуги' },
  services: { title: 'Наші Послуги', subtitle: 'Професійний догляд за кожною деталлю вашого автомобіля', duration: '{minutes} хв', from: 'від' },
  why: { title: 'Чому Passlavski?', mobile: { title: 'Мобільний Сервіс', desc: 'Ми приїжджаємо до вашої локації — дім, офіс або будь-яке зручне місце.' }, professional: { title: 'Професійне Обладнання', desc: 'Найкращі інструменти та преміальні продукти для бездоганного результату.' }, experience: { title: 'Команда Експертів', desc: 'Роки досвіду з усіма типами автомобілів та систем фарбування.' }, guarantee: { title: 'Гарантія Якості', desc: '100% гарантія задоволення або ми повернемося виправити.' } },
  cta: { title: 'Готові Перетворити Ваш Автомобіль?', subtitle: 'Запишіться сьогодні та відчуйте різницю Passlavski.', button: 'Записатися' },
  booking: { title: 'Запис на Сесію', steps: { services: 'Послуги', datetime: 'Дата і Час', contact: 'Контакти', photos: 'Фото', confirm: 'Підтвердження' }, selectServices: 'Оберіть Послуги', selectDate: 'Оберіть Дату', selectTime: 'Оберіть Час', totalDuration: 'Загальна Тривалість', minutes: 'хв', noSlots: 'Немає доступних слотів на цю дату', notWorkingDay: 'Цей день не є робочим', contact: { phone: 'Номер Телефону', phonePlaceholder: '+380 50 123 4567', email: 'Email (необов\'язково)', emailPlaceholder: 'ваш@email.com', whatsapp: 'WhatsApp', whatsappPlaceholder: '+380 50 123 4567', instagram: 'Instagram', instagramPlaceholder: '@вашакаунт', address: 'Ваша Адреса / Локація', addressPlaceholder: 'вул. Головна 123, Місто', notes: 'Додаткові Нотатки (необов\'язково)', notesPlaceholder: 'Особливі побажання або деталі про ваш автомобіль...' }, photos: { title: 'Завантажити Фото Автомобіля', subtitle: 'Додайте фото вашого авто для точнішої оцінки часу роботи', dropzone: 'Перетягніть фото сюди або натисніть для вибору', maxSize: 'Макс 10МБ на файл' }, summary: { title: 'Підсумок Запису', services: 'Обрані Послуги', dateTime: 'Дата та Час', duration: 'Загальна Тривалість', contact: 'Контактна Інформація', photos: 'Фото', photosCount: '{count} фото додано', submit: 'Підтвердити Запис', submitting: 'Надсилається...' }, success: { title: 'Запис Підтверджено!', message: 'Дякуємо за вибір Passlavski. Ми зв\'яжемося з вами найближчим часом.', backHome: 'На Головну', bookAnother: 'Записатися Ще' }, next: 'Далі', prev: 'Назад' },
  admin: { login: { title: 'Вхід Адміністратора', username: 'Логін', password: 'Пароль', submit: 'Увійти', error: 'Невірні дані' }, tabs: { bookings: 'Записи', services: 'Послуги', schedule: 'Розклад' }, bookings: { title: 'Управління Записами', noBookings: 'Записів ще немає', status: 'Статус', customer: 'Клієнт', services: 'Послуги', dateTime: 'Дата та Час', duration: 'Тривалість', actions: 'Дії', confirm: 'Підтвердити', complete: 'Завершити', cancel: 'Скасувати', delete: 'Видалити', viewPhotos: 'Переглянути Фото' }, services: { title: 'Управління Послугами', addNew: 'Додати Послугу', name: 'Назва', description: 'Опис', duration: 'Тривалість (хв)', price: 'Ціна', active: 'Активна', save: 'Зберегти', cancel: 'Скасувати', edit: 'Редагувати', delete: 'Деактивувати' }, schedule: { title: 'Робочий Розклад', day: 'День', start: 'Початок', end: 'Кінець', working: 'Робочий', save: 'Зберегти Розклад', breaks: 'Налаштування Перерв', breakBetween: 'Перерва Між Записами (хв)', lunchStart: 'Початок Обіду', lunchEnd: 'Кінець Обіду', saveBreaks: 'Зберегти Перерви' }, logout: 'Вийти' },
  days: { MONDAY: 'Понеділок', TUESDAY: 'Вівторок', WEDNESDAY: 'Середа', THURSDAY: 'Четвер', FRIDAY: 'П\'ятниця', SATURDAY: 'Субота', SUNDAY: 'Неділя' },
  footer: { rights: '© 2026 Passlavski. Всі права захищені.', tagline: 'Преміальний Мобільний Авто Детейлінг' }
}
